export const jobRoles = [
  "Student",
  "Unemployed",
  "Prefer not to say",
  "Account Executive",
  "Account Manager",
  "Accountant",
  "Acupuncturist",
  "Actor",
  "Advertising Manager",
  "Aerospace Engineer",
  "Air Traffic Controller",
  "Airline Pilot",
  "Animal Control Officer",
  "Animator",
  "Archaeologist",
  "Architect",
  "Artist",
  "Astronaut",
  "Astronomer",
  "Athlete",
  "Attorney",
  "Audiologist",
  "Automotive Mechanic",
  "Baker",
  "Bank Branch Manager",
  "Bank Teller",
  "Banker",
  "Barista",
  "Bartender",
  "Biological Scientist",
  "Biomedical Engineer",
  "Biomedical Scientist",
  "Blacksmith",
  "Botanist",
  "Brand Manager",
  "Bricklayer",
  "Bus Driver",
  "Business Analyst",
  "Cable Installer",
  "Cable Technician",
  "Cartographer",
  "Cartoonist",
  "Casino Dealer",
  "Cell Biologist",
  "Chiropractor",
  "Chocolatier",
  "Civil Engineer",
  "Civil Rights Attorney",
  "Claims Adjuster",
  "Clinical Psychologist",
  "Comedian",
  "Compliance Officer",
  "Computer Programmer",
  "Computer Support Specialist",
  "Conservationist",
  "Construction Worker",
  "Copywriter",
  "Corporate Trainer",
  "Criminal Investigator",
  "Cruise Ship Director",
  "Cryptographer",
  "Dancer",
  "Data Analyst",
  "Data Scientist",
  "Debt Collector",
  "Dental Hygienist",
  "Dentist",
  "Dermatologist",
  "Dermatopathologist",
  "Designer",
  "Detective",
  "Dietitian",
  "Digital Marketer",
  "Diplomat",
  "Diving Instructor",
  "Doctor",
  "Drone Pilot",
  "Economist",
  "Editor",
  "Electrician",
  "Emergency Dispatcher",
  "Emergency Medical Technician (EMT)",
  "Environmental Engineer",
  "Environmental Scientist",
  "Ethical Hacker",
  "Event Planner",
  "Exterminator",
  "Famous Person",
  "Farmer",
  "Fashion Designer",
  "Fashion Model",
  "Fictional Character",
  "Film Director",
  "Financial Advisor",
  "Financial Analyst",
  "Fire Inspector",
  "Firefighter",
  "Fisherman",
  "Flight Attendant",
  "Flight Instructor",
  "Florist",
  "Forklift Operator",
  "Forensic Scientist",
  "Forester",
  "Furniture Designer",
  "Game Designer",
  "Game Warden",
  "Genetic Counselor",
  "Geneticist",
  "Geologist",
  "Glassblower",
  "Graphic Designer",
  "Guidance Counselor",
  "Gynecologist",
  "HAZWOPER Specialist",
  "Hairstylist",
  "Hazardous Waste Manager",
  "Health Educator",
  "Historian",
  "Historical Preservationist",
  "Home Health Aide",
  "Hotel Manager",
  "Human Resources Manager",
  "Illustrator",
  "Immigration Officer",
  "Immunologist",
  "Industrial Designer",
  "Information Security Analyst",
  "Insurance Agent",
  "Insurance Broker",
  "Interior Designer",
  "Interpreter",
  "IT Manager",
  "Jazz Musician",
  "Jeweler",
  "Journalist",
  "Judge",
  "Kinesiologist",
  "Laboratory Technician",
  "Landscaper",
  "Landscape Architect",
  "Lawyer",
  "Legal Secretary",
  "Lifeguard",
  "Linguist",
  "Machine Operator",
  "Machinist",
  "Maintenance Worker",
  "Makeup Artist",
  "Management Consultant",
  "Manager",
  "Manufacturing Engineer",
  "Marine Biologist",
  "Market Research Analyst",
  "Marketing Manager",
  "Marketing Specialist",
  "Materials Scientist",
  "Math Teacher",
  "Mathematician",
  "Mechanic",
  "Mechanical Engineer",
  "Media Planner",
  "Medical Assistant",
  "Medical Laboratory Technician",
  "Medical Records Technician",
  "Medical Transcriptionist",
  "Mediator",
  "Meteorologist",
  "Microbiologist",
  "Midwife",
  "Mobile App Developer",
  "Model",
  "Museum Curator",
  "Music Producer",
  "Musician",
  "Nuclear Engineer",
  "Nurse",
  "Nutritionist",
  "Obstetrician",
  "Occupational Therapist",
  "Oceanographer",
  "Office Manager",
  "Operating Room Nurse",
  "Optometrist",
  "Orthodontist",
  "Orthopedic Surgeon",
  "Painter",
  "Park Ranger",
  "Paramedic",
  "Patent Attorney",
  "Pediatrician",
  "Personal Trainer",
  "Pet Groomer",
  "Pharmacist",
  "Phlebotomist",
  "Photographer",
  "Physical Therapist",
  "Physician",
  "Physician Assistant",
  "Physicist",
  "Plumber",
  "Police Dispatcher",
  "Police Officer",
  "Political Analyst",
  "Political Consultant",
  "Postsecondary Teacher",
  "Product Manager",
  "Production Manager",
  "Professional Athlete",
  "Professor",
  "Programmer",
  "Project Manager",
  "Prosthodontist",
  "Psychiatrist",
  "Psychologist",
  "Public Defender",
  "Public Relations Specialist",
  "Quality Assurance Tester",
  "Radiation Therapist",
  "Radiologic Technologist",
  "Radiologist",
  "Real Estate Agent",
  "Real Estate Broker",
  "Receptionist",
  "Recreational Therapist",
  "Research Scientist",
  "Restaurant Manager",
  "Risk Analyst",
  "Robotics Engineer",
  "Sales Manager",
  "Sales Representative",
  "Sailor",
  "Scientist",
  "Screenwriter",
  "Sculptor",
  "Security Guard",
  "Set Designer",
  "Social Media Influencer",
  "Social Media Manager",
  "Social Worker",
  "Software Developer",
  "Software Engineer",
  "Special Effects Artist",
  "Sports Agent",
  "Sports Coach",
  "Statistician",
  "Stockbroker",
  "Substance Abuse Counselor",
  "Surgeon",
  "Surveyor",
  "Systems Analyst",
  "Tax Preparer",
  "Taxi Driver",
  "Taxidermist",
  "Teacher",
  "Technical Writer",
  "Technology Manager",
  "Telemarketer",
  "Textile Designer",
  "Tour Guide",
  "Translator",
  "Travel Agent",
  "Truck Driver",
  "Urologist",
  "Urban Planner",
  "User Experience Designer",
  "Veterinarian",
  "Veterinary Technician",
  "Video Game Designer",
  "Video Game Tester",
  "Voice Actor",
  "Waiter/Waitress",
  "Web Designer",
  "Web Developer",
  "Wedding Planner",
  "Welder",
  "Wildlife Biologist",
  "Writer",
  "Youth Counselor",
  "Zookeeper",
  "Zoologist",
];




export const jobRolesObj = jobRoles.map((role) => ({name: role}))